golang: Move cgocheck2 to GOEXPERIMENT
On macOS with golang 1.21.0:

  fatal error: cgocheck > 1 mode is no longer supported at runtime. Use GOEXPERIMENT=cgocheck2 at build time instead.

apparently caused by this change:

  https://go-review.googlesource.com/c/go/+/447778/12

However older versions of golang reject this with:

  go: unknown GOEXPERIMENT cgocheck2

so we need to test the version of golang.